module.exports = {
  notes: [
    {
      type: 'category',
      label: '*nix',
      items: [
        'notes/unix/unix',
        'notes/unix/vim',
        'notes/unix/emacs',
        'notes/unix/readline',
        'notes/unix/tmux',
        'notes/unix/git',
        'notes/unix/grep',
        'notes/unix/sed',
        'notes/unix/awk',
        'notes/unix/jq',
        'notes/unix/find',
        'notes/unix/xargs',
        'notes/unix/fzf',
        'notes/unix/curl',
        'notes/unix/wget',
        'notes/unix/ssh',
        'notes/unix/pgp',
        'notes/unix/rsync',
        'notes/unix/shells',
        'notes/unix/archival',
        'notes/unix/window-managers',
        'notes/unix/terminal-emulators',
        'notes/unix/text-editors-and-ides',
        'notes/unix/browsers',
      ],
    },
    {
      type: 'category',
      label: 'Programming',
      items: [
        'notes/programming/regex',
        'notes/programming/lorem-ipsum',
        'notes/programming/python',
        'notes/programming/javascript',
        'notes/programming/typescript',
        'notes/programming/haskell',
        'notes/programming/rust',
        'notes/programming/css',
        'notes/programming/html',
      ],
    },
    {
      type: 'category',
      label: 'Recreational mathematics',
      items: [
        'notes/recreational-mathematics/speedcubing',
        'notes/recreational-mathematics/cfop',
        'notes/recreational-mathematics/mathemagics',
        'notes/recreational-mathematics/chess',
        'notes/recreational-mathematics/card-tricks',
        'notes/recreational-mathematics/mathematical-constants',
        'notes/recreational-mathematics/mnemonics',
      ],
    },
    {
      type: 'category',
      label: 'Mathematics',
      items: [
        {
          type: 'category',
          label: 'Calculus',
          items: [
            'notes/mathematics/calculus/limits',
            'notes/mathematics/calculus/differential-calculus',
            'notes/mathematics/calculus/integral-calculus',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Misc',
      items: [
        'notes/misc/websites',
        'notes/misc/rss',
        'notes/misc/privacy',
        'notes/misc/poems',
        'notes/misc/quotes',
        'notes/misc/misc',
      ],
    },
    {
      type: 'category',
      label: 'Book notes',
      items: ['notes/books/python-tricks'],
    },
  ],
  links: [
    'links/programming',
    'links/courses',
    'links/knowledge-repositories',
    'links/unix',
    'links/oss',
    'links/software',
    'links/stem',
    'links/art',
    'links/puzzles',
    'links/reddit',
    'links/youtube',
    'links/twitch',
    'links/books',
    'links/comics',
    'links/podcasts',
    'links/ebooks',
    'links/articles',
    'links/misc',
  ],
}
